name: anticp3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - Bio==1.7.1
      - joblib==1.4.2
      - numpy==1.26.4
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - tqdm==4.67.1
